#!/usr/bin/env bash
#Script to install and configure HAProxy load balance

 set -e

 WEB01_IP="10.227.127.137"
 WEB02_IP="10.227.95.216"

 echo "Updating system..."
 sudo apt-get update -y

 echo "Installing HAProxy..."
 sudo apt-get install -y haproxy

 echo "Setting hostname for lb-01..."
 sudo hostnamectl set-hostname "lb-01"

 echo "Configuring HAProxy..."

 sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 ${WEB01_IP}:80 check
    server web-02 ${WEB02_IP}:80 check
EOF

echo "Enabling and restarting HAProxy..."
sudo systemctl enable haproxy
sudo systemctl restart haproxy

echo "HAProxy installation and configuration completed successfully."
